mysite/cart/urls.py
from django.conf.urls import *
from . import views
from django.conf.urls import url, patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.show_cart, {'template_name':'cart/cart.html' }, name='show_cart'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^send/$', views.send_email, name='send_email'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += staticfiles_urlpatterns()

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shop import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="home"),
	url(r'^testindex$', views.TestIndexView.as_view(), name="testhome"),
    url(r'^contacts/$', views.ContactsView, name="contacts"),
    #url(r'^contacts2/$', views.Contacts2View, name="contacts2"),
    url(r'^about/$', views.AboutView, name="about"),
    url(r'^pay/$', views.PayView, name="pay"),
    url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^news/$', views.NewsView, {'template_name':'shop/news.html'}, name='news'),
    url(r'^news/(?P<article_slug>[-\w]+)/$', views.show_article, {'template_name':'shop/article.html'}, name='shop_article'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += staticfiles_urlpatterns()

mysite/cart/models.py
from django.db import models
from shop.models import Item

class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    item = models.ForeignKey('shop.Item', unique=False)

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']

    def total(self):
        return self.quantity * self.item.price

    def name(self):
        return self.item.name

    def price(self):
        return self.item.price

    def get_absolute_url(self):
        return self.item.get_absolute_url()

    def augment_quantity(self, quantity):
        self.quantity = self.quantity + int(quantity)
        self.save()


class Order_Status(models.Model):
    CONFIRMATION = ''
    WAITING_FOR_DELIEVERY = ''
    SOLD_WAITING_FOR_DELIEVERY = ''
    SOLD = ''
        
    status_choices = (
        (CONFIRMATION, 'Ждёт подтверждения'),
        (WAITING_FOR_DELIEVERY, 'Ждет доставки'),
        (SOLD_WAITING_FOR_DELIEVERY, 'Продано, ждет доставки'),
        (SOLD, 'Продано'),
    )

    status_name = models.CharField(max_length=50, choices=status_choices, default=CONFIRMATION)

    def __str__(self):
        return self.status_name

class Order(models.Model):
    WHEN_DELIEVERED = ''
    CARD = ''

    payment_choices = (
        (WHEN_DELIEVERED, 'Наличными курьеру'),
        (CARD, 'Оплата картой'),
    )

    order_id = models.CharField(max_length=50)
    item = models.ManyToManyField(CartItem)
    phone = models.CharField(max_length=50)
    adress = models.CharField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.ForeignKey(Order_Status)
    subtotal = models.DecimalField(max_digits=15, decimal_places=2)
    payment = models.CharField(max_length=50, choices=payment_choices, default=WHEN_DELIEVERED)


# Create your models here.

mysite/cart/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.core.mail import send_mail, EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from . import cart
CART_ID_SESSION_KEY = 'cart_id'

def show_cart(request, template_name="cart/cart.html"):
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata['submit'] == 'X':
            cart.remove_from_cart(request)
        if postdata['submit'] == 'Обновить':
            cart.update_cart(request)
    cart_items = cart.get_cart_items(request)
#    cart_item_count = cart.cart_item_count(request)
    page_title = 'Корзина'
    cart_subtotal = cart.cart_subtotal(request)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def checkout(request, template_name="cart/checkout.html"):
    cart_items = cart.get_cart_items(request)
    page_title = 'Оформление заказа'
    cart_subtotal = cart.cart_subtotal(request)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))




# отправка информации о заказе на почту
def send_email(request, template_name="cart/send.html"):


    if request.method == 'POST':
        postdata = request.POST.copy()
        name = postdata.get('name','')
        email = postdata.get('email','')
        phone = postdata.get('phone','')
        adress = postdata.get('adress','')
        comment = postdata.get('comment','')
        obtaining = postdata.get('obtaining','')
        #paytype = postdata.get('paytype','') /// </p><p> Способ оплаты: '+ paytype +'; - из строки html-content

        cart_items = cart.get_cart_items(request)
        cart_subtotal = cart.cart_subtotal(request)
        # тема и почтовые ящики(от кого и кому)
        subject, from_email, to = 'Новый заказ ', 'sender@mastertree.ru', 'info@mastertree.ru'
        text_content = ''

        itemhtml = ''
        for item in cart_items:
            itemhtml+='Наименование: <strong>' + item.item.item_name + '</strong>; Количество: <strong>' + str(item.quantity) + '</strong>.<br/>'    

        html_content = '<p> ФИО: '+ name +';</p><p> Почта: '+ email +';</p><p>Телефон: '+ str(phone) +';</p><p> Адресс: '+ adress +';</p></p> Примечание: '+ comment +';</p><p> Способ получения: '+ obtaining +';</p> <p>Сумма: <strong>'+ str(cart_subtotal)+ '</strong>.</p></br>' + itemhtml
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        subject_4customer, from_email_4customer, to_4customer = 'Ваш заказ принят', 'info@mastertree.ru', email
        text_content_4customer = ''
        msg_to_customer = EmailMultiAlternatives(subject_4customer, text_content_4customer, from_email_4customer, [to_4customer])
        html_content_to_customer = '<p>Телефон: '+ str(phone) +';</p><p> Адресс: '+ adress +';</p><p> Способ получения: '+ obtaining +';</p> <p>Сумма: <strong>'+ str(cart_subtotal)+ '</strong>.</p></br>' + itemhtml
        msg_to_customer.attach_alternative(html_content_to_customer, "text/html")
        msg_to_customer.send()

        page_title = 'Оформление заказа'
        request.session[CART_ID_SESSION_KEY]=''
        return render_to_response(template_name, locals(), context_instance=RequestContext(request))
    else: return HttpResponseRedirect(reverse('home'))


# Create your views here.

mysite/cart/templates/cart/cart.html
{% extends "shop/shop.html" %}
{% load shop_filter %}


{% block content %}

<table summary="Your Shopping Cart" id="shopping_cart">
    <h1>Ваша корзина</h1>
    <thead>
    <tr>
        <th scope="col">Наименование</th>
        <th scope="col">Цена</th>
        <th></th>
        <th></th>
        <th></th>
        <th scope="col" class="right">Итого</th>
      	
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th class="right" colspan="5">К оплате:</th>
        <th class="right">{{ cart_subtotal|currency }}</th>
    </tr>
    {% if cart_items %}
    <tr>
        <th class="right" colspan="6">
            <a href="{% url 'cart:checkout' %}">Оформить заказ</a>
        </th>
    </tr>
    {% endif %}
    </tfoot>
    <tbody>
    {% if cart_items %}
        {% for item in cart_items %}
        <tr>
        <td>{{ item.item_name }}
            <a href="{{ item.get_absolute_url }}" class="cart">
                {{ item.item.item_name }}
            </a>
        </td>
        <td>{{ item.price|currency }}</td>
        <td class="right">
        <form  method="post" action="." class="cart" >{% csrf_token %}
        
        <div class="quantity">
            <input type="number" name="quantity" value="{{ item.quantity }}" id="quantity" min="1" max="9" step="1" />
        </div>
        <input type="hidden" name="item_id" value="{{ item.id }}" />
        </td>
        <td>
        <input class="buttons" type="submit" name="submit"  value="Обновить" />
        </form>
        </td>
        <td>
        <form style="" method="post" action="." class="cart">{% csrf_token %}
        <input type="hidden" name="item_id" value="{{ item.id }}" />
        <input class="buttons" type="submit" name="submit" value="X" />
        
        </form>
        </td>
        <td class="right">{{ item.total|currency }}</td>

        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="6" style="height:30px;">Ваша корзина пуста</td>
        </tr>
    {% endif %}
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/numbers.js"></script>
{% endblock %}

mysite/cart/templates/cart/checkout.html
{% extends 'shop/shop.html' %}

{% block content %}

    <form method="post" action="{% url 'cart:send_email' %}">{% csrf_token %}
		
      <div style="width:500px; margin: 0 auto;">
        <h3 class="checkout_label">Информация о получателе:</h3>
        <div class="name">
            <input class="checkinput" placeholder="ФИО" type="text" name="name" maxlength="100">
        </div>
        
        <div class="email">
          <input required class="checkinput" placeholder="Email" type="email" name="email" maxlength="100">
        </div>

        <div class="phone">
          <input required class="checkinput" id="phone" placeholder="Телефон" type="text" name="phone" maxlength="100">
        </div>

        <div class="adress">
          <input class="checkinput" placeholder="Адрес" type="text" name="adress">
        </div>

        <div class="comment">
           <textarea class="checkinput" name="comment" placeholder="Примечание" cols="40" rows="4"></textarea>
        </div>


      <!--/div-->


        <!--div class="pay_type">
            <label for="pay_type">Способ оплаты:</label>
            <select name="pay_type">
                <option disabled>Выберети способ оплаты</option>
                <option selected value="Оплата наличными курьеру">Оплата наличными курьеру</option>
                <option value="Оплата картой">Оплата картой</option>
            </select>
        </div-->
	<!--div style="width:45%; float:right"-->
      	<div class="obtaining" >
           
          	<h3 class="checkout_label">Способ получения:</h3>
          
          <input type="radio" name="obtaining" value="Самовывоз" style="margin: 0 10px 0"> <b>Самовывоз</b>
          <input type="radio" name="obtaining" value="Доставка" style="margin: 0 10px 0"> <b>Доставка</b>
            <!--select required class="checkinput" name="obtaining">
              	
                <option value="Самовывоз">Самовывоз</option>
                <option value="Доставка">Доставка</option>
            </select-->
        </div>
      	
      	<!--h3 class="checkout_label">Способ оплаты:</h3>
          <input class="checkbuttons" type="submit" name="paytype" value="Оплата наличными"/>
          <input class="checkbuttons" type="submit" name="paytype" value="Оплата картой"/-->
      	<input class="checkbuttons" type="submit" name="paytype" value="Оформить заказ"/>
    	
      </div>
      
    </form>  

    <!--a href="{% url 'cart:send_email' %}">Подтвердить заказ</a-->

    <script type="text/javascript" src="{{ MEDIA_URL }}js/phone_form/jquery.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/phone_form/jquery.maskedinput-1.2.2.js"></script>

<script type="text/javascript">
    jQuery(function($) {
        $.mask.definitions['~']='[+-]';
        $('#phone').mask('(999) 999-9999');
    });</script>


{% endblock %}

mysite/cart/templates/cart/send.html
{% extends "shop/shop.html" %}

{% block content %}
	<h4>Ваша заявка принята</h4>
{% endblock %}