mysite/cart/urls.py
from django.conf.urls import *
from . import views
from django.conf.urls import url, patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.show_cart, {'template_name':'cart/cart.html' }, name='show_cart'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^send/$', views.send_email, name='send_email'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += staticfiles_urlpatterns()

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shop import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="home"),
	url(r'^testindex$', views.TestIndexView.as_view(), name="testhome"),
    url(r'^contacts/$', views.ContactsView, name="contacts"),
    #url(r'^contacts2/$', views.Contacts2View, name="contacts2"),
    url(r'^about/$', views.AboutView, name="about"),
    url(r'^pay/$', views.PayView, name="pay"),
    url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^news/$', views.NewsView, {'template_name':'shop/news.html'}, name='news'),
    url(r'^news/(?P<article_slug>[-\w]+)/$', views.show_article, {'template_name':'shop/article.html'}, name='shop_article'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += staticfiles_urlpatterns()

mysite/shop/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import *

from django.conf.urls import url, patterns
from . import views
#from .views import detail
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'shop'
urlpatterns = [
    #url(r'^$', views.ShopView.as_view(), name='shopv'),
    url(r'^$', views.ShopView, {'template_name':'shop/shop.html'}, name='shopv'),
#    url(r'^about/$', views.AboutView, name='about'),
    url(r'^contacts/$', views.ContactsView, name='contacts'),
    #url(r'^$', 'index', {'template_name':'shop/index.html'}, 'shop_home'),
    #url(r'^category/(?P<category_slug>[-\w]+)/$', 'show_category', {'template_name':'shop/category.html'}, 'shop_category'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.show_category, {'template_name':'shop/category.html'}, name='shop_category'),
    url(r'^item/(?P<item_slug>[-\w]+)/$', views.show_item, {'template_name':'shop/item.html'}, name='shop_item'),
    url(r'^send/$', views.subscribe, name='subscribe'),
    url(r'^call/$', views.callback, name='callback'),
    url(r'^comment/$', views.add_comment, name='add_comment'),

#    url(r'^$', views.IndexView.as_view(), name='index'),
#    url(r'^items/(?P<pk>[0-9]+)/$', detail, name='detail'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += staticfiles_urlpatterns()

mysite/shop/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Item



class ItemAdminForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        def clean_price(self):
            if self.cleaned_data['price'] <= 0:
                raise forms.ValidationError('Price must be greater than zero.')
            return self.cleaned_data['price']

class ItemAddToCartForm(forms.Form):
    #quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2', 'value':'1', 'class':'quantity'}), error_messages={'invalid':'Введите правильное число.'}, min_value=1)
    item_slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ItemAddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.request:

            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError("Куки должны быть включены.")
        return self.cleaned_data

mysite/shop/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext
from .models import Item, Category, ItemImage, SliderImage, ItemComment, Article
from django.core.mail import send_mail, EmailMultiAlternatives

from django.core import urlresolvers
from cart import cart
from .forms import ItemAddToCartForm


#def index(request, template_name='shop/index.html'):
#    page_title = 'Резные иконы'
#    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def subscribe(request):
    if request.method == 'POST':
        postdata = request.POST.copy()
        submail = postdata.get('submail','')
        sub_subject, sub_from_email, sub_to = 'Добавление подписчика', 'sender@mastertree.ru', 'info@mastertree.ru'
        sub_text_content = ''
        sub_html_content = '<p> Почта: '+ submail +';</p>'
        sub_msg = EmailMultiAlternatives(sub_subject, sub_text_content, sub_from_email, [sub_to])
        sub_msg.attach_alternative(sub_html_content, "text/html")
        sub_msg.send()
        return redirect(request.META['HTTP_REFERER'])
    else: return HttpResponseRedirect(reverse('home'))

def callback(request):
    if request.method == 'POST':
        postdata = request.POST.copy()
        callphone = postdata.get('callphone','')
        call_subject, call_from_email, call_to_email = 'Обратный звонок', 'sender@mastertree.ru', 'info@mastertree.ru'
        call_text_content = ''
        call_html_content = '<p> Телефон: '+ callphone +';</p>'
        call_msg = EmailMultiAlternatives(call_subject, call_text_content, call_from_email, [call_to_email])
        call_msg.attach_alternative(call_html_content, "text/html")
        call_msg.send()
        return redirect(request.META['HTTP_REFERER'])
    else: return HttpResponseRedirect(reverse('home'))

def add_comment(request):
    if request.method == 'POST':
        postdata = request.POST.copy()
		############################################
        i = postdata.get('item','')
        item = Item.objects.get(id=i)
        item_name = item.item_name
        comment = postdata.get('comment','')
        comm_name = postdata.get('comm_name','')
        comm_email = postdata.get('comm_email','')
        ic = ItemComment()
        ic.item = item
        ic.item_name = item_name
        ic.comment = comment
        ic.comm_name = comm_name
        ic.comm_email = comm_email
        ic.save()
        return redirect(request.META['HTTP_REFERER'])
    else: return HttpResponseRedirect(reverse('home'))

def show_category(request, category_slug, template_name='shop/category.html'):
    c = get_object_or_404(Category, slug=category_slug)
    items = c.item_set.all()
    page_title = c.category_name
    meta_keywords = c.meta_keywords
    meta_description = c.meta_description
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def show_item(request, item_slug, template_name='shop/item.html'):
    i = get_object_or_404(Item, slug=item_slug)
    categories = i.categories.filter(is_active=True)
    page_title = i.item_name
    meta_keywords = i.meta_keywords
    meta_description = i.meta_description
    comments = i.itemcomment_set.all()

    if request.method == 'POST':
        postdata = request.POST.copy()
        form = ItemAddToCartForm(request, postdata)
        if form.is_valid():
            cart.add_to_cart(request)
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = urlresolvers.reverse('cart:show_cart')
            #return HttpResponseRedirect(url) - перенаправление в корзину(убрано)
            return redirect(request.META['HTTP_REFERER'])
            #return render_to_response(template_name, locals(), context_instance=RequestContext(request)) - так оно думало, что кук нет
    else:
        form = ItemAddToCartForm(request=request, label_suffix=':')
    form.fields['item_slug'].widget.attrs['value'] = item_slug
    request.session.set_test_cookie()
#    return render_to_response("shop/item.html", locals(), context_instance=RequestContext(request))

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))



def show_article(request, article_slug, template_name='shop/article.html'):
    a = get_object_or_404(Article, slug=article_slug)
    page_title = a.article_name
    meta_keywords = a.meta_keywords
    meta_description = a.meta_description

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def NewsView(request, template_name='shop/news.html'):
    page_title = 'Новости'
    meta_keywords = 'Новости, Новости Master Tree'
    meta_description = 'Новости MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))



class IndexView(generic.ListView):
    template_name = 'shop/index.html'
    context_object_name = 'slider_images'

    def get_queryset(self):
        return SliderImage.objects.all()


class TestIndexView(generic.ListView):
    template_name = 'shop/testindex.html'
    context_object_name = 'slider_images'
    def get_queryset(self):
        return SliderImage.objects.all()

#class ShopView(generic.ListView):
#    template_name = 'shop/shop.html'
#
#    def get_queryset(self):
#        return Item.objects.all()

def ShopView(request, template_name='shop/shop.html'):
    page_title = 'Каталог'
    meta_keywords = 'Каталог, Резные иконы'
    meta_description = 'Каталог MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def AboutView(request, template_name="shop/about.html"):
    page_title = 'О нас'
    meta_keywords = 'О нас, MasterTree, Адрес MasterTree, Телефоны MasterTree'
    meta_description = 'О MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def PayView(request, template_name="shop/pay.html"):
    page_title = 'Доставка и оплата'
    meta_keywords = 'Доставка и оплата, MasterTree, Доставка и оплата MasterTree'
    meta_description = 'Доставка и оплата MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))

def ContactsView(request, template_name="shop/contacts.html"):
    if request.method == 'POST':
        postdata = request.POST.copy()
        mess_name = postdata.get('mess_name','')
        mess_email = postdata.get('mess_email','')
        mess_subject = postdata.get('mess_subject','')
        mess_message = postdata.get('mess_message','')
        mess_from_email, mess_to = 'sender@mastertree.ru', 'info@mastertree.ru'
        mess_text_content = ''
        mess_html_content = '<p> ФИО: ' + mess_name +';</p><p> Почта: '+ mess_email +';</p><br><p> Сообщение: </p><p>' + mess_message + '</p>'
        mess_msg = EmailMultiAlternatives(mess_subject, mess_text_content, mess_from_email, [mess_to])
        mess_msg.attach_alternative(mess_html_content, "text/html")
        mess_msg.send()
        return redirect(request.META['HTTP_REFERER'])
    page_title = 'Контакты'
    meta_keywords = 'Контакты, MasterTree, Адрес MasterTree, Телефоны MasterTree'
    meta_description = 'Контакты MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def Contacts2View(request, template_name="shop/contacts2.html"):
    if request.method == 'POST':
        postdata = request.POST.copy()
        mess_name = postdata.get('mess_name','')
        mess_email = postdata.get('mess_email','')
        mess_subject = postdata.get('mess_subject','')
        mess_message = postdata.get('mess_message','')
        mess_from_email, mess_to = 'sender@mastertree.ru', 'info@mastertree.ru'
        mess_text_content = ''
        mess_html_content = '<p> ФИО: ' + mess_name +';</p><p> Почта: '+ mess_email +';</p><br><p> Сообщение: </p><p>' + mess_message + '</p>'
        mess_msg = EmailMultiAlternatives(mess_subject, mess_text_content, mess_from_email, [mess_to])
        mess_msg.attach_alternative(mess_html_content, "text/html")
        mess_msg.send()
        return redirect(request.META['HTTP_REFERER'])
    page_title = 'Контакты'
    meta_keywords = 'Контакты, MasterTree, Адрес MasterTree, Телефоны MasterTree'
    meta_description = 'Контакты MasterTree'
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


#def detail(request, pk):
 #   item = get_object_or_404(Item, pk=pk)
  #  return render(request, 'shop/detail.html', {'item': item})

#class DetailView(generic.DetailView):
#    model = Item
#    template_name = 'shop/detail.html'
#    def item_page(request, pk):
#        item = Item.objects.get(pk=pk)
#        image_list = item.images.all()

#    def get_queryset(self):
#        return Item.objects.all()
#        image_list = item.images.all()

mysite/shop/templates/shop/base.html
<!DOCTYPE html>
{% load shop_tags %}
<html>

<head>
    <link rel="Stylesheet" type="text/css" href="{{ MEDIA_URL }}css_v12_2.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	<link rel="icon" type="image/jpg" href="/favicon.jpg" />
    <title>{% block title %} {% if page_title %}{{ page_title }} - {% endif %}
        {{ site_name }}{% endblock %}</title>
    <meta name="keywords" content="{{ meta_keywords }}" />
    <meta name="description" content="{{ meta_description }}" />
  	<meta name="author" content="Daniel Markelov" />

    <!-- Стили для модулей -->
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}magnific.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}style5.css" />

        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}slick/slick.css"/>
	<!-- Add the new slick-theme.css if you want the default styling -->
	<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}slick/slick-theme.css"/>

    <!-- Скрипты для подключенных модулей -->
    <script src="{{ MEDIA_URL }}js/modernizr.custom.63321.js"></script>
  	
	
</head>


<body > 
	
    <header>
    <!--Здесь и далее class="wrapper" используется для оцентровки материала -->
        <div class="wrapper">
        <!-- Главное меню сайта -->
            <nav>
                <div class="logo-box">
                    <h1 class="logo">
                        <a href="/">
                            <img id="logo" src="{{ MEDIA_URL }}img/logo.png" width="113" height="80">
                        </a>
                    </h1>
                </div>


                {% include "tags/navigation.html" %}


            </nav>
                <div class="cart_box" >
                    {% cart_box request %}
                </div>
        </div>
    </header>

	<!-- Раздел с контентом -->
      
	<main >
		<div class="wrapper">

            {% block site_wrapper %}{% endblock %}

	    </div>
	</main>
      


	<footer>

	<!-- Верх футера (серая часть, где адрес,соцсети и подписка) -->
	<div class="wrapper">
		<!-- Раздел с адресом -->
		<div class="footh" style="width:27%;">

			<h6  class="fh">СОЦСЕТИ</h6>
		
			<div class="line_foot"></div>
			
			<div >
				
				<div class="sn">
					<a href="http://vk.com/club126883775" target="_blank" >
                      <img  src="{{ MEDIA_URL }}img/vk.png"  >
					</a>
				</div>
				<div class="sn" >
					<a href="https://facebook.com/mastertreevn/" target="_blank" >
                      <img src="{{ MEDIA_URL }}img/fb.png" >
					</a>
				</div>
				<div class="sn" >
					<a href="https://instagram.com/master_tree_vn" target="_blank" >
                      <img src="{{ MEDIA_URL }}img/inst.png"  >
					</a>
				</div>
			</div>
		</div>
      
		<div class="footh" >
			
			<h6 class="fh">ОБРАТНЫЙ ЗВОНОК</h6>

			<div class="line_foot"></div>
			
			<div >
              <form method="post" action="{% url 'shop:callback' %}">{% csrf_token %}
				<p>Оставьте свой телефон. Наш оператор с вами свяжется в ближайшее время.</p>
				<input required id="callinput" placeholder="Телефон" type="text" name="callphone" maxlength="100"></br>
				<input type="submit" id="callback" value="Жду звонка">
              </form>
			</div>
		</div>	
		<!-- Раздел с подпиской -->
		<div class="footh" style="float:right; padding-right: 10px;">
			
			<h6 class="fh">ПРИСОЕДИНЯЙТЕСЬ</h6>
			
			
			<div class="line_foot"></div>
			
			<div >
              <form method="post" action="{% url 'shop:subscribe' %}">{% csrf_token %}
				<p>Подпишитесь на обновления</p></br></br>
				<input required id="subinput" placeholder="Email" name="submail" type="email"></br>
				<input type="submit" id="subscribe" value="Подписаться">
              </form>
			</div>
		</div>
		<!-- Раздел с соцсетями -->
		
	</div>
	
	<div class="cleaner"></div>
	
	<!-- Низ футера(черная полоска) -->
	
	<div id="footers-bottom">
		<div class="wrapper">
		
			<div class="footb" >
			
				<div style="left: 5px; top: 10px; width: 24px; height: 29px;" >
					<img src="{{ MEDIA_URL }}img/box.png" >
				</div>
				
				<div style="left: 50px; width: 438px;  top: 16px;" >
					<p>БЫСТРАЯ ДОСТАВКА В ЛЮБОЙ ГОРОД РОССИИ</p>
				</div>
				
				<div style="left: 803px; width: 166px; top: 14px;" >
					<p>© 2016 Master Tree.</p>
				</div>
			</div>
		</div>
	</div>
	
</footer>


	

</body>

</html>

mysite/shop/templates/shop/base2.html
<!DOCTYPE html>
{% load shop_tags %}
<html>

<head>
    <link rel="Stylesheet" type="text/css" href="{{ MEDIA_URL }}css_v12_2.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block title %} {% if page_title %}{{ page_title }} - {% endif %}
        {{ site_name }}{% endblock %}</title>
    <meta name="keywords" content="{{ meta_keywords }}" />
    <meta name="description" content="{{ meta_description }}" />
  	<meta name="author" content="Daniel Markelov" />

    <!-- Стили для модулей -->
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}magnific.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}style5.css" />

        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}slick/slick.css"/>
	<!-- Add the new slick-theme.css if you want the default styling -->
	<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}slick/slick-theme.css"/>

    <!-- Скрипты для подключенных модулей -->
    <script src="{{ MEDIA_URL }}js/modernizr.custom.63321.js"></script>
	
</head>


<body > 
	
    <header>
    <!--Здесь и далее class="wrapper" используется для оцентровки материала -->
        <div class="wrapper">
        <!-- Главное меню сайта -->
            <nav>
                <div class="logo-box">
                    <h1 class="logo">
                        <a href="/">
                            <img id="logo" src="{{ MEDIA_URL }}img/logo.png" width="113" height="80">
                        </a>
                    </h1>
                </div>


                {% include "tags/nav.html" %}
				  	<div class="cart_box" >
                 {% cart_box request %}
      </div>
			
            </nav>
			
        </div>
    </header>

	<!-- Раздел с контентом -->
      
	<main >


            {% block site_wrapper %}{% endblock %}


	</main>
      


	<footer>

	<!-- Верх футера (серая часть, где адрес,соцсети и подписка) -->
	<div class="wrapper">
		<!-- Раздел с адресом -->
      
      <div class="footh">

			<h6  class="fh">СОЦСЕТИ</h6>
		
			<div class="line_foot"></div>
			
			<div >
				
				<div class="sn">
					<a href="http://vk.com/club126883775" target="_blank" >
                      <img  src="{{ MEDIA_URL }}img/vk.png"  >
					</a>
				</div>
				<div class="sn" >
					<a href="https://facebook.com/mastertreevn/" target="_blank" >
                      <img src="{{ MEDIA_URL }}img/fb.png" >
					</a>
				</div>
				<div class="sn" >
					<a href="https://instagram.com/master_tree_vn" target="_blank" >
                      <img src="{{ MEDIA_URL }}img/inst.png"  >
					</a>
				</div>
			</div>
		</div>
      
		<div class="footh" >
			
			<h6 class="fh">ОБРАТНЫЙ ЗВОНОК</h6>

			<div class="line_foot"></div>
			
			<div >
              <form method="post" action="{% url 'shop:callback' %}">{% csrf_token %}
				<p>Оставьте свой телефон. Наш оператор с вами свяжется в ближайшее время.</p>
				<input required id="callinput" placeholder="Телефон" type="text" name="callphone" maxlength="100"></br>
				<input type="submit" id="callback" value="Жду звонка">
              </form>
			</div>
		</div>	
		<!-- Раздел с подпиской -->
		<div class="footh" style="float:right; padding-right: 10px;">
			
			<h6 class="fh">ПРИСОЕДИНЯЙТЕСЬ</h6>
			
			
			<div class="line_foot"></div>
			
			<div >
              <form method="post" action="{% url 'shop:subscribe' %}">{% csrf_token %}
				<p>Подпишитесь на обновления</p></br></br>
				<input required id="subinput" placeholder="Email" name="submail" type="email"></br>
				<input type="submit" id="subscribe" value="Подписаться">
              </form>
			</div>
		</div>
		<!-- Раздел с соцсетями -->
		
	</div>
	
	<div class="cleaner"></div>
	
	<!-- Низ футера(черная полоска) -->
	
	<div id="footers-bottom">
		<div class="wrapper">
		
			<div class="footb" >
			
				<div style="left: 5px; top: 10px; width: 24px; height: 29px;" >
					<img src="{{ MEDIA_URL }}img/box.png" >
				</div>
				
				<div style="left: 50px; width: 438px;  top: 16px;" >
					<p>БЫСТРАЯ ДОСТАВКА В ЛЮБОЙ ГОРОД РОССИИ</p>
				</div>
				
				<div style="left: 803px; width: 166px; top: 14px;" >
					<p>© 2016 Master Tree.</p>
				</div>
			</div>
		</div>
	</div>
	
</footer>


<script type="text/javascript" src="{{ MEDIA_URL }}js/phone_form/jquery.maskedinput-1.2.2.js"></script>

<script type="text/javascript">
    jQuery(function($) {
        $.mask.definitions['~']='[+-]';
        $('#callinput').mask('(999) 999-9999');
    });</script>

</body>

</html>

mysite/shop/templates/shop/item.html
{% extends "shop/shop.html" %}
{% load thumbnail %}
{% load shop_filter %}
{% load tz %}

{% block content %}
    <div class="bread" style="color:gray;">
        <a href="{% url 'shop:shopv' %}" style="color:black"> Каталог </a>
        >
        В категори{{ categories.count|pluralize:"и,ях" }}:
            {% for c in categories %}
                <a style="color:black" href="{{ c.get_absolute_url }}">{{ c.category_name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        >
        {{ i.item_name }}
	</div>
        <br /><br />
<div class="wrapper">

		</br>
		<div style="width:59%; float:left;">
		<section class="magnific-all">
			<a href="{{ i.preview.url }}" class="magnific item">
                <img src="{{ i.preview.url}}" width=90% style="float:left;" onload="imgLoaded(this)"/>
			</a>
            <div style="float:left; margin-top: 5px;" >
                {% for image in i.images.all %}
                    {% thumbnail image.item_image "100x100" crop="center" as im %}
                        <a href="{{ image.item_image.url }}" class="magnific item">
                            <img src="{{ im.url }}" width={{ im.width }} height={{ im.height }} onload="imgLoaded(this)"/>
                        </a>
                    {% endthumbnail %}
                {% endfor %}


            </div>
		</section>


		</div>

		<div style="width:39%; float:right; text-align:left;">
			<h2 style="margin-top: 0px; float:left; width:100%">{{ i.item_name }}</h2>

			<div id="pricediv" style="float:left; margin: 10px 0; width:100%" >
                <h4>
                    {% if i.sale_price %}
                        Старая цена: <del> {{ i.old_price|currency }}</del>
                        <br />
                        Цена: {{ i.price|currency }}
                    {% else %}
                        Цена: {{ i.price|currency }}
                    {% endif %}
                </h4>
            </div>
            <br /><br />

            <form method="post" action="" class="cart">
                {% csrf_token %}
                {{ form.as_p }}
                <br />

				<input type="submit" name="add_to_cart" class="add__to__cart__button" value="Добавить в корзину"></p>
            </form>


			<p class="content" style="text-align:left; clear:both">{{ i.description|ljust:"10"|linebreaksbr }}</p>
   		</div>
<div class="items__bottom_wrapp">
        <div style="width=100%; clear:both;">

			<hr/>
			<div class="slide" style="clear:both">
				<label id="s3" for="slide2" onclick="javascript:if(document.getElementById('slide2').checked){ document.getElementById('s4').innerHTML='+' } else { document.getElementById('s4').innerHTML='—' } ">Описание
					<label id="s4" for="slide2" onclick="javascript:if(document.getElementById('slide2').checked){ document.getElementById('s4').innerHTML='+' } else { document.getElementById('s4').innerHTML='—' } ">—</label>
				</label>
				<input type="checkbox" checked id="slide2"/>
					<p class="content" id="s5" style="text-align:justify; clear:both">{{ i.about|ljust:"10"|linebreaksbr }}</p>

			</div>

			<h3>Отзывы:</h3>

			{% for comment in comments %}
              <div style=" width:100%; text-align: justify; margin-bottom:10px; ">
                  <h4> {{ comment.comm_name }} </h4>
                <h5 style="margin-bottom: 5px;"> {{ comment.created_at|date:"d.m.Y H:i:s"  }} </h5>
                  <p> {{ comment.comment }} </p>

              </div>
    		{% endfor %}
    </div>

          	<div style="height:auto; margin-bottom:50px;">
              <form method="post" action="{% url 'shop:add_comment' %}">{% csrf_token %}
                <h3>Оставьте свой отзыв</h3>
				<input type="hidden" name="item" value="{{ i.id }}">

		<div style="width:49.8%; float:left; height:auto;">
          <div class="name">
              <input style="height: 35px;" required class="checkinput" placeholder="ФИО" type="text" name="comm_name" maxlength="100">
          </div>
          <div class="email">
            <input style="height: 35px;"  class="checkinput" placeholder="Email для обратной связи ( необязательно )" type="email" name="comm_email" maxlength="100">
          </div>
        </div>


        <div style="width:49.8%; float:right; height:auto;" >
             <textarea style="height:78px;"  required class="checkinput" name="comment" placeholder="Сообщение" cols="40" rows="4"></textarea>
			 
        </div>
                
				<input type="submit" id="subscribe" value="Добавить отзыв">
              </form>
			</div>
  </div>
	<!-- Скрипты для подключенных модулей -->
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

	<script type="text/javascript" src="{{ MEDIA_URL }}js/numbers.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/magnigic.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/gallery.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.dropdown.js"></script>
	<script type="text/javascript">
		
		$( function() {
			
			$( '#cd-dropdown' ).dropdown( {
				gutter : 5,
				stack : false,
				slidingIn : 100
			} );
		});

	</script>


{% endblock %}

mysite/shop/templates/shop/news.html
{% extends "shop/base.html" %}
{% load thumbnail %}
{% load shop_filter %}
{% load shop_tags %}
{% block site_wrapper %}

<h1>Новости</h1>

                {% article_list request.path %}

{% endblock %}